"""Tests for the Synthea dynamic data generator."""

import json
import tempfile
from pathlib import Path

import pytest

from ingest.simulators.synthea_generator import SyntheaGenerator
from ingest.simulators.base_simulator import PatientProfile, ClinicalScenario


@pytest.fixture
def sample_synthea_bundle():
    """Minimal Synthea-like FHIR transaction bundle."""
    return {
        "resourceType": "Bundle",
        "type": "transaction",
        "entry": [
            {
                "fullUrl": "urn:uuid:test-patient-001",
                "resource": {
                    "resourceType": "Patient",
                    "id": "test-patient-001",
                    "text": {
                        "status": "generated",
                        "div": "<div>Generated by Synthea</div>"
                    },
                    "identifier": [
                        {
                            "system": "https://github.com/synthetichealth/synthea",
                            "value": "test-patient-001"
                        },
                        {
                            "type": {
                                "coding": [{"system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                            "code": "MR", "display": "Medical Record Number"}],
                                "text": "Medical Record Number"
                            },
                            "system": "http://hospital.smarthealthit.org",
                            "value": "test-patient-001"
                        }
                    ],
                    "name": [{"use": "official", "family": "Smith", "given": ["John", "Robert"]}],
                    "telecom": [{"system": "phone", "value": "555-123-4567", "use": "home"}],
                    "gender": "male",
                    "birthDate": "1985-03-15",
                    "address": [{"line": ["123 Main St"], "city": "Boston", "state": "MA",
                                 "postalCode": "02101", "country": "US"}],
                },
                "request": {"method": "POST", "url": "Patient"}
            },
            {
                "fullUrl": "urn:uuid:test-condition-001",
                "resource": {
                    "resourceType": "Condition",
                    "id": "test-condition-001",
                    "code": {
                        "coding": [{"system": "http://snomed.info/sct",
                                    "code": "38341003",
                                    "display": "Hypertensive disorder"}]
                    },
                    "subject": {"reference": "urn:uuid:test-patient-001"},
                },
                "request": {"method": "POST", "url": "Condition"}
            },
            {
                "fullUrl": "urn:uuid:test-encounter-001",
                "resource": {
                    "resourceType": "Encounter",
                    "id": "test-encounter-001",
                    "status": "finished",
                    "class": {"system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
                              "code": "AMB"},
                    "type": [{"coding": [{"system": "http://snomed.info/sct",
                                          "code": "162673000",
                                          "display": "General examination of patient"}]}],
                    "subject": {"reference": "urn:uuid:test-patient-001"},
                    "period": {"start": "2026-01-15T10:00:00Z", "end": "2026-01-15T11:00:00Z"},
                },
                "request": {"method": "POST", "url": "Encounter"}
            },
            {
                "fullUrl": "urn:uuid:test-obs-001",
                "resource": {
                    "resourceType": "Observation",
                    "id": "test-obs-001",
                    "status": "final",
                    "code": {
                        "coding": [{"system": "http://loinc.org",
                                    "code": "718-7",
                                    "display": "Hemoglobin"}]
                    },
                    "subject": {"reference": "urn:uuid:test-patient-001"},
                    "valueQuantity": {"value": 14.2, "unit": "g/dL"},
                },
                "request": {"method": "POST", "url": "Observation"}
            },
            {
                "fullUrl": "urn:uuid:test-med-001",
                "resource": {
                    "resourceType": "MedicationRequest",
                    "id": "test-med-001",
                    "status": "active",
                    "intent": "order",
                    "medicationCodeableConcept": {
                        "coding": [{"system": "http://www.nlm.nih.gov/research/umls/rxnorm",
                                    "code": "316049",
                                    "display": "Lisinopril 10 MG Oral Tablet"}]
                    },
                    "subject": {"reference": "urn:uuid:test-patient-001"},
                },
                "request": {"method": "POST", "url": "MedicationRequest"}
            },
        ]
    }


@pytest.fixture
def generator():
    return SyntheaGenerator()


class TestSyntheaGenerator:

    def test_load_from_files(self, generator, sample_synthea_bundle, tmp_path):
        """Test loading Synthea bundles from JSON files."""
        filepath = tmp_path / "patient_001.json"
        filepath.write_text(json.dumps(sample_synthea_bundle))

        bundles = generator.load_from_files(str(filepath))
        assert len(bundles) == 1
        assert bundles[0]["resourceType"] == "Bundle"
        assert len(bundles[0]["entry"]) == 5

    def test_load_from_directory(self, generator, sample_synthea_bundle, tmp_path):
        """Test loading all bundles from a directory."""
        for i in range(3):
            fp = tmp_path / f"patient_{i:03d}.json"
            fp.write_text(json.dumps(sample_synthea_bundle))

        bundles = generator.load_from_directory(str(tmp_path))
        assert len(bundles) == 3

    def test_extract_profiles(self, generator, sample_synthea_bundle):
        """Test extracting PatientProfile + ClinicalScenario from bundles."""
        results = generator.extract_profiles([sample_synthea_bundle])
        assert len(results) == 1

        profile, scenario = results[0]

        # Check profile
        assert isinstance(profile, PatientProfile)
        assert profile.given_name == "John"
        assert profile.family_name == "Smith"
        assert profile.name == "John Smith"
        assert profile.dob == "1985-03-15"
        assert profile.gender == "male"
        assert "test-patient-001" in profile.mrn

    def test_extract_scenario_diagnoses(self, generator, sample_synthea_bundle):
        """Test that diagnoses are correctly extracted."""
        results = generator.extract_profiles([sample_synthea_bundle])
        _, scenario = results[0]

        assert isinstance(scenario, ClinicalScenario)
        assert len(scenario.diagnoses) >= 1
        # The hypertension condition should be mapped to ICD-10
        codes = [d["code"] for d in scenario.diagnoses]
        assert "I10" in codes

    def test_extract_scenario_labs(self, generator, sample_synthea_bundle):
        """Test that lab values are extracted from observations."""
        results = generator.extract_profiles([sample_synthea_bundle])
        _, scenario = results[0]

        # Should have extracted hemoglobin from the observation
        lab_names = [lab["name"] for lab in scenario.labs]
        assert "Hemoglobin" in lab_names

        hgb = next(l for l in scenario.labs if l["name"] == "Hemoglobin")
        assert hgb["value"] == 14.2
        assert hgb["code"] == "718-7"

    def test_extract_scenario_medications(self, generator, sample_synthea_bundle):
        """Test that medications are extracted."""
        results = generator.extract_profiles([sample_synthea_bundle])
        _, scenario = results[0]

        assert len(scenario.medications) >= 1
        assert any("Lisinopril" in m for m in scenario.medications)

    def test_extract_scenario_vitals(self, generator, sample_synthea_bundle):
        """Test that vital signs are reasonable."""
        results = generator.extract_profiles([sample_synthea_bundle])
        _, scenario = results[0]

        # Hypertension -> cardiac category
        assert 60 <= scenario.baseline_hr <= 140
        assert 80 <= scenario.baseline_bp_sys <= 200
        assert 50 <= scenario.baseline_bp_dia <= 110
        assert 85 <= scenario.baseline_spo2 <= 100
        assert 35.0 <= scenario.baseline_temp <= 39.0
        assert 10 <= scenario.baseline_rr <= 40

    def test_extract_generates_abha_id(self, generator, sample_synthea_bundle):
        """Test that ABHA IDs are deterministically generated."""
        results = generator.extract_profiles([sample_synthea_bundle])
        profile, _ = results[0]

        assert profile.abha_id.startswith("ABHA-")
        # Run again - should be deterministic
        results2 = generator.extract_profiles([sample_synthea_bundle])
        assert results2[0][0].abha_id == profile.abha_id

    def test_empty_bundle(self, generator):
        """Test handling of empty bundle."""
        empty = {"resourceType": "Bundle", "type": "transaction", "entry": []}
        results = generator.extract_profiles([empty])
        assert len(results) == 0

    def test_bundle_without_conditions(self, generator):
        """Test handling of bundle with patient but no conditions."""
        bundle = {
            "resourceType": "Bundle",
            "type": "transaction",
            "entry": [{
                "fullUrl": "urn:uuid:minimal-patient",
                "resource": {
                    "resourceType": "Patient",
                    "id": "minimal-patient",
                    "name": [{"use": "official", "family": "Doe", "given": ["Jane"]}],
                    "gender": "female",
                    "birthDate": "1990-06-01",
                },
                "request": {"method": "POST", "url": "Patient"}
            }]
        }
        results = generator.extract_profiles([bundle])
        assert len(results) == 1
        profile, scenario = results[0]
        assert profile.name == "Jane Doe"
        # Should have default scenario
        assert len(scenario.diagnoses) >= 1
        assert len(scenario.labs) >= 1

    def test_multiple_bundles(self, generator, sample_synthea_bundle):
        """Test extracting from multiple bundles."""
        # Create a second bundle with different patient
        bundle2 = json.loads(json.dumps(sample_synthea_bundle))
        for entry in bundle2["entry"]:
            if entry["resource"]["resourceType"] == "Patient":
                entry["resource"]["name"] = [
                    {"use": "official", "family": "Jones", "given": ["Alice"]}
                ]
                entry["resource"]["gender"] = "female"
                entry["resource"]["id"] = "test-patient-002"
                break

        results = generator.extract_profiles([sample_synthea_bundle, bundle2])
        assert len(results) == 2
        names = [r[0].name for r in results]
        assert "John Smith" in names
        assert "Alice Jones" in names


class TestLoadRealSyntheaFiles:
    """Tests using actual Synthea sample files if available."""

    SAMPLE_DIR = Path(__file__).parent.parent / "sample_data" / "synthea"

    @pytest.mark.skipif(
        not (Path(__file__).parent.parent / "sample_data" / "synthea").exists(),
        reason="No Synthea sample files available"
    )
    def test_load_real_synthea_files(self):
        generator = SyntheaGenerator()
        bundles = generator.load_from_directory(str(self.SAMPLE_DIR))
        assert len(bundles) > 0

        results = generator.extract_profiles(bundles)
        assert len(results) > 0

        for profile, scenario in results:
            assert profile.name
            assert profile.dob
            assert profile.gender in ("male", "female", "other", "unknown")
            assert scenario.chief_complaint
            assert len(scenario.diagnoses) > 0
            assert scenario.baseline_hr > 0
            assert scenario.baseline_bp_sys > 0
