"""Tests for the Synthea FHIR bundle adapter."""

import json
from pathlib import Path

import pytest

from ingest.adapters.synthea_adapter import SyntheaAdapter


@pytest.fixture
def synthea_bundle():
    """Minimal Synthea-like FHIR transaction bundle."""
    return {
        "resourceType": "Bundle",
        "type": "transaction",
        "entry": [
            {
                "fullUrl": "urn:uuid:adapter-test-001",
                "resource": {
                    "resourceType": "Patient",
                    "id": "adapter-test-001",
                    "text": {
                        "status": "generated",
                        "div": "<div>Generated by Synthea</div>"
                    },
                    "identifier": [
                        {
                            "system": "https://github.com/synthetichealth/synthea",
                            "value": "adapter-test-001"
                        },
                        {
                            "type": {
                                "coding": [{"system": "http://terminology.hl7.org/CodeSystem/v2-0203",
                                            "code": "MR"}],
                            },
                            "system": "http://hospital.smarthealthit.org",
                            "value": "adapter-test-001"
                        }
                    ],
                    "name": [{"use": "official", "family": "TestFamily", "given": ["TestGiven"]}],
                    "telecom": [{"system": "phone", "value": "555-000-1111"}],
                    "gender": "female",
                    "birthDate": "1992-07-20",
                    "address": [{"line": ["456 Test Ave"], "city": "Cambridge", "state": "MA",
                                 "postalCode": "02139"}],
                },
                "request": {"method": "POST", "url": "Patient"}
            },
            {
                "fullUrl": "urn:uuid:adapter-enc-001",
                "resource": {
                    "resourceType": "Encounter",
                    "id": "adapter-enc-001",
                    "status": "finished",
                    "class": {"system": "http://terminology.hl7.org/CodeSystem/v3-ActCode",
                              "code": "AMB"},
                    "subject": {"reference": "urn:uuid:adapter-test-001"},
                    "period": {"start": "2026-01-10T08:00:00Z"},
                },
                "request": {"method": "POST", "url": "Encounter"}
            },
            {
                "fullUrl": "urn:uuid:adapter-obs-001",
                "resource": {
                    "resourceType": "Observation",
                    "id": "adapter-obs-001",
                    "status": "final",
                    "code": {"coding": [{"system": "http://loinc.org", "code": "8867-4",
                                         "display": "Heart rate"}]},
                    "subject": {"reference": "urn:uuid:adapter-test-001"},
                    "valueQuantity": {"value": 78, "unit": "/min"},
                },
                "request": {"method": "POST", "url": "Observation"}
            },
        ]
    }


@pytest.fixture
def adapter():
    return SyntheaAdapter()


class TestSyntheaAdapter:

    def test_source_type(self, adapter):
        assert adapter.source_type == "synthea_fhir"

    def test_supports_synthea_file(self, adapter, synthea_bundle, tmp_path):
        filepath = tmp_path / "synthea_patient.json"
        filepath.write_text(json.dumps(synthea_bundle))
        assert adapter.supports(str(filepath)) is True

    def test_rejects_non_json(self, adapter, tmp_path):
        filepath = tmp_path / "data.xml"
        filepath.write_text("<xml>not json</xml>")
        assert adapter.supports(str(filepath)) is False

    def test_rejects_non_bundle_json(self, adapter, tmp_path):
        filepath = tmp_path / "other.json"
        filepath.write_text(json.dumps({"resourceType": "Patient", "id": "123"}))
        assert adapter.supports(str(filepath)) is False

    def test_rejects_non_transaction_bundle(self, adapter, tmp_path):
        filepath = tmp_path / "collection.json"
        filepath.write_text(json.dumps({
            "resourceType": "Bundle", "type": "collection", "entry": []
        }))
        assert adapter.supports(str(filepath)) is False

    def test_parse_extracts_identity(self, adapter, synthea_bundle, tmp_path):
        filepath = tmp_path / "patient.json"
        filepath.write_text(json.dumps(synthea_bundle))

        result = adapter.parse(str(filepath))

        assert result.patient_identity.given_name == "TestGiven"
        assert result.patient_identity.family_name == "TestFamily"
        assert result.patient_identity.gender == "female"
        assert result.patient_identity.birth_date == "1992-07-20"
        assert result.patient_identity.mrn == "adapter-test-001"
        assert result.patient_identity.address_city == "Cambridge"

    def test_parse_extracts_resources(self, adapter, synthea_bundle, tmp_path):
        filepath = tmp_path / "patient.json"
        filepath.write_text(json.dumps(synthea_bundle))

        result = adapter.parse(str(filepath))

        # Should have Encounter and Observation (Patient is separate)
        assert len(result.fhir_resources) >= 2
        resource_types = [r.get_resource_type() for r in result.fhir_resources]
        assert "Encounter" in resource_types
        assert "Observation" in resource_types

    def test_parse_metadata(self, adapter, synthea_bundle, tmp_path):
        filepath = tmp_path / "patient.json"
        filepath.write_text(json.dumps(synthea_bundle))

        result = adapter.parse(str(filepath))

        assert result.source_type == "synthea_fhir"
        assert result.raw_metadata["bundle_type"] == "transaction"
        assert result.raw_metadata["total_entries"] == 3
        assert result.raw_metadata["resource_counts"]["Patient"] == 1


class TestSyntheaAdapterRealFiles:
    """Test with real Synthea sample files if available."""

    SAMPLE_DIR = Path(__file__).parent.parent / "sample_data" / "_synthea_raw" / "fhir"

    @pytest.mark.skipif(
        not (Path(__file__).parent.parent / "sample_data" / "_synthea_raw" / "fhir").exists(),
        reason="No Synthea sample files available"
    )
    def test_supports_real_files(self):
        adapter = SyntheaAdapter()
        for f in sorted(self.SAMPLE_DIR.glob("*.json"))[:1]:
            assert adapter.supports(str(f)) is True

    @pytest.mark.skipif(
        not (Path(__file__).parent.parent / "sample_data" / "_synthea_raw" / "fhir").exists(),
        reason="No Synthea sample files available"
    )
    def test_parse_real_files(self):
        adapter = SyntheaAdapter()
        for f in sorted(self.SAMPLE_DIR.glob("*.json"))[:1]:
            result = adapter.parse(str(f))
            assert result.patient_identity.full_name
            assert result.patient_identity.birth_date
            assert len(result.fhir_resources) > 0
            print(f"  {f.name}: {result.patient_identity.full_name} -> "
                  f"{len(result.fhir_resources)} resources")
